module ErrorCodes
  FIELD_VALIDATION      = "FIELD_VALIDATION"
  BUSINESS_VALIDATION   = "BUSINESS_VALIDATION"
  NOT_FOUND             = "NOT_FOUND"
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
end
